spring.application.name=testSetup


spring.datasource.url=jdbc:postgresql://springboot-postgres.czsuy2owugar.ap-south-1.rds.amazonaws.com:5432/learning_site_db
spring.datasource.driver-class-name=org.postgresql.Driver

# ? Yahan apna sahi username aur password daalo
spring.datasource.username=postgres
spring.datasource.password=nomiso1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=2MB
